# Generated by Django 6.1.1 on 2026-09-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscountCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Номер телефону"),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=200, verbose_name="Повне ім'я власника"
                    ),
                ),
                (
                    "discount_percent",
                    models.PositiveSmallIntegerField(verbose_name="Відсоток знижки"),
                ),
                (
                    "bonus_points",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Накопичені бонуси"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата останнього використання",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дисконтна картка",
                "verbose_name_plural": "Дисконтні картки",
            },
        ),
    ]
