# Generated by Django 6.1.1 on 2026-09-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_import_notebook_cards"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountcard",
            name="first_name",
            field=models.CharField(default="", max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AddField(
            model_name="discountcard",
            name="last_name",
            field=models.CharField(default="", max_length=100, verbose_name="Прізвище"),
        ),
    ]
