# Generated by Django 6.1.1 on 2026-09-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_split_full_name"),
    ]

    operations = [
        # Додано для відкату. На схему бази не впливає.
        migrations.AlterField(
            model_name="discountcard",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Повне ім'я власника"
            ),
        ),
        migrations.RemoveField(
            model_name="discountcard",
            name="full_name",
        ),
    ]
