# Generated by Django 6.1.1 on 2026-09-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0006_normalize_phones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountcard",
            name="last_used_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Дата останнього використання",
            ),
        ),
        migrations.AlterField(
            model_name="discountcard",
            name="phone",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Номер телефону"
            ),
        ),
    ]
